name: CI

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npx serverless deploy --conceal --stage prd
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
        CHANNEL_CREATED_NOTIFY_CHANNEL: ${{ secrets.CHANNEL_CREATED_NOTIFY_CHANNEL }}
        TEAM_JOIN_NOTIFY_CHANNEL: ${{ secrets.CHANNEL_CREATED_NOTIFY_CHANNEL }}
